openapi: 3.0.2
info:
  title: Encryptor
  contact:
    name: Ahmed Safwat
    email: ahmed-881994@hotmail.com
  description: |
    Encrypt plain text using simple encryption *i.e*: ***Caesar***, ***Morse***, etc.

    Available methods:

      * Caesar
      * Morse
      * Numeric
      * Inverse Numeric

    ---

    [GitHub repo](https://github.com/ahmed-881994/encryptorAPI)
  version: 1.0.0
servers:
  - url: 127.0.0.1:8000
    description: localhost
paths:
  /caesar:
    post:
      summary: Encrypts plain text using the Caesar method
      operationId: caesar_caesar_post
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EncryptCaesarRq'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EncryptRs'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /morse:
    post:
      summary: Encrypts plain text using the Morse method
      operationId: morse_morse_post
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EncryptRq'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EncryptRs'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /numeric:
    post:
      summary: Encrypts plain text using the Numeric method
      operationId: numeric_numeric_post
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EncryptRq'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EncryptRs'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /reversenumeric:
    post:
      summary: Encrypts plain text using the Reverse Numeric method
      operationId: reversenumeric_reversenumeric_post
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EncryptRq'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EncryptRs'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    EncryptCaesarRq:
      title: EncryptCaesarRq
      required:
        - plainText
        - language
        - shift
      type: object
      properties:
        plainText:
          title: Plaintext
          type: string
        language:
          $ref: '#/components/schemas/langEnum'
        shift:
          title: Shift
          type: integer
    EncryptRq:
      title: EncryptRq
      required:
        - plainText
        - language
      type: object
      properties:
        plainText:
          title: Plaintext
          type: string
        language:
          $ref: '#/components/schemas/langEnum'
    EncryptRs:
      title: EncryptRs
      required:
        - cypherText
      type: object
      properties:
        cypherText:
          title: Cyphertext
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    langEnum:
      title: langEnum
      enum:
        - AR
        - EN
      type: string
      description: An enumeration.
